<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>packets</string>
	</array>
	<key>name</key>
	<string>RG Packets</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#other</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#packet</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comment</key>
		<dict>
			<key>begin</key>
			<string>(^[\t]+//)</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>comment.line.double-slash.cpppackets</string>
		</dict>
		<key>optional</key>
		<dict>
			<key>begin</key>
			<string>\,</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.cpppackets</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=[$"])</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#signature_optional_group</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#optional_type</string>
				</dict>
				<dict>
					<key>match</key>
					<string>.+</string>
					<key>name</key>
					<string>invalid.illegal.cpppackets</string>
				</dict>
			</array>
		</dict>
		<key>optional_type</key>
		<dict>
			<key>name</key>
			<string>support.class.cpppackets</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>[NBWILSFA]</string>
					<key>name</key>
					<string>support.class.cpppackets</string>
				</dict>
				<dict>
					<key>match</key>
					<string>.+</string>
					<key>name</key>
					<string>invalid.illegal.cpppackets</string>
				</dict>
			</array>
		</dict>
		<key>other</key>
		<dict>
			<key>name</key>
			<string>comment.line.double-slash.cpppackets</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(^\t+[^"\t].*$)</string>
					<key>name</key>
					<string>comment.line.double-slash.cpppackets</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(^[^\t])</string>
					<key>end</key>
					<string>$</string>
					<key>name</key>
					<string>comment.line.double-slash.cpppackets</string>
				</dict>
			</array>
		</dict>
		<key>packet</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#signature</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#title</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#struct</string>
				</dict>
			</array>
		</dict>
		<key>separated_type</key>
		<dict>
			<key>name</key>
			<string>support.function.cpppackets</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?&lt;=[:\[])[NBWILSFA]</string>
					<key>name</key>
					<string>support.function.cpppackets</string>
				</dict>
				<dict>
					<key>match</key>
					<string>.+</string>
					<key>name</key>
					<string>invalid.illegal.cpppackets</string>
				</dict>
			</array>
		</dict>
		<key>signature</key>
		<dict>
			<key>begin</key>
			<string>(^)([\t]*)(")</string>
			<key>beginCaptures</key>
			<dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.quoted.double.cpppackets</string>
				</dict>
			</dict>
			<key>end</key>
			<string>("\,)([\t]+)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.quoted.double.cpppackets</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#optional</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#signature_group</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#type</string>
				</dict>
			</array>
		</dict>
		<key>signature_group</key>
		<dict>
			<key>begin</key>
			<string>\[</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.cpppackets</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\]</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.cpppackets</string>
				</dict>
			</dict>
			<key>name</key>
			<string>support.function.cpppackets</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#signature_group</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#type</string>
				</dict>
				<dict>
					<key>match</key>
					<string>.+</string>
					<key>name</key>
					<string>invalid.illegal.cpppackets</string>
				</dict>
			</array>
		</dict>
		<key>signature_optional_group</key>
		<dict>
			<key>begin</key>
			<string>\[</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.cpppackets</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\]</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.cpppackets</string>
				</dict>
			</dict>
			<key>name</key>
			<string>support.class.cpppackets</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#optional_type</string>
				</dict>
				<dict>
					<key>match</key>
					<string>.+</string>
					<key>name</key>
					<string>invalid.illegal.cpppackets</string>
				</dict>
			</array>
		</dict>
		<key>struct</key>
		<dict>
			<key>begin</key>
			<string>(?&lt;= )</string>
			<key>end</key>
			<string>(?=$)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#struct_field</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#var_group</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\[</string>
					<key>name</key>
					<string>invalid.illegal.cpppackets</string>
				</dict>
			</array>
		</dict>
		<key>struct_field</key>
		<dict>
			<key>begin</key>
			<string>([a-zA-Z][a-zA-Z0-9_]*)\:</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.cpppackets</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\,)|($)|(?=\])</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>support.class.cpppackets</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.cpppackets</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#var_group</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#separated_type</string>
				</dict>
			</array>
		</dict>
		<key>title</key>
		<dict>
			<key>name</key>
			<string>keyword.control.cpppackets</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>comment.block.documentation</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.cpppackets</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.cpppackets</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.cpppackets</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.cpppackets</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.cpppackets</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(// )([A-Z_]+)(\()([1-9][0-9]*)(\))(; ?)</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>comment.block.documentation</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.cpppackets</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.cpppackets</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(// )(MIN_TYPE)(;)</string>
				</dict>
			</array>
		</dict>
		<key>type</key>
		<dict>
			<key>name</key>
			<string>support.function.cpppackets</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>[NBWILSFA]</string>
					<key>name</key>
					<string>support.function.cpppackets</string>
				</dict>
				<dict>
					<key>match</key>
					<string>.+</string>
					<key>name</key>
					<string>invalid.illegal.cpppackets</string>
				</dict>
			</array>
		</dict>
		<key>var_group</key>
		<dict>
			<key>begin</key>
			<string>\[</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.cpppackets</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\])(?=(\,)|(\])|$)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.cpppackets</string>
				</dict>
			</dict>
			<key>name</key>
			<string>support.function.cpppackets</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#var_group</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#struct_field</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#group</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[a-zA-Z]{2,}</string>
					<key>name</key>
					<string>invalid.illegal.cpppackets</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.cpppackets</string>
	<key>uuid</key>
	<string>bdd91146-233f-408e-b4bc-83feb5c6a4eb</string>
</dict>
</plist>
